# Generated by Django 5.0.4 on 2024-06-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0007_prescription_medicine_alter_prescription_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='zalopay_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
