# Generated by Django 5.0.4 on 2024-06-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0008_bill_zalopay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='nurse',
        ),
    ]
