# """
# Django settings for clinic_manager project.
#
# Generated by 'django-admin startproject' using Django 5.0.4.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/5.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.0/ref/settings/
# """
#
# from pathlib import Path
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-0jpo=x9qvt-*8h5@fae&@z50tvl*iu$#3#e*@$1ww&=h6844@j'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.7']
#
# # Application definition
#
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'clinic_app',
#     'rest_framework',
#     'drf_yasg',
#     'oauth2_provider',
#     'corsheaders',
#     'social_django'     # đăng nhập bằng fb
#     # 'ckeditor_uploader'
# ]
#
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'corsheaders.middleware.CorsMiddleware', # CORS
#     'social_django.middleware.SocialAuthExceptionMiddleware',   #fb
#     # 'social_django.context_processors.backends'
# ]
#
# ROOT_URLCONF = 'clinic_manager.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'clinic_manager.wsgi.application'
#
# # Database
# # https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'clinic1',
#         'USER': 'root',
#         'PASSWORD': '123456',
#         'HOST': ''  # mặc định localhost
#     }
# }
#
# # Password validation
# # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
# # Internationalization
# # https://docs.djangoproject.com/en/5.0/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_TZ = True
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.0/howto/static-files/
#
# STATIC_URL = 'static/'
#
# # Default primary key field type
# # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
#
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#
# import cloudinary
#
# cloudinary.config(
#     cloud_name="dlkfozznl",
#     api_key="216689541712763",
#     api_secret="m_IQI6lLGClNtrf8ZeuG97Do4Fs"
# )
#
# AUTH_USER_MODEL = 'clinic_app.User'
#
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     )
# }
#
# # setting cho facebook
# # AUTHENTICATION_BACKENDS = [
# #     'social_core.backends.facebook.FacebookOAuth2',
# #     'django.contrib.auth.backends.ModelBackend',
# # ]
# # #
# # LOGIN_URL = 'login'
# # LOGIN_REDIRECT_URL = 'home'
# # LOGOUT_URL = 'logout'
# # LOGOUT_REDIRECT_URL = 'login'
# # #
# # SOCIAL_AUTH_FACEBOOK_KEY = '893789679094872'
# # SOCIAL_AUTH_FACEBOOK_SECRET = '1c4cf1353d5a18d9b66b934a73a74336'
# # #
# # # #for extra infor
# # SOCIAL_AUTH_FACEBOOK_SCOPE = [
# #     'email',
# # ]
#
# CORS_ALLOW_ALL_ORIGINS = True
#
#
#
# # client_id = "VZJWZH78HUZqjJoSExSw1DMfdYfAfaZqRgWDRx0L"
# # client_secret = "iiux3RY6awF8kOXrnJHcqIUI2upEiCXggg5tmJfQUvLmlQs30DCyDCbeQai5FNegAcEJX9TgpJvpRIuJTiE5b0xq0dYgkk3gUpVFjNXuMn6XrgsNKGdnmeDYgK24PeZL"
#
# #setting mail
# EMAIL_HOST_USER  ="levanhieu26012003@gmail.com"
# MAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_PASSWORD = "qjpw wfda arwp emls"
#
#
# MAX_APPOINTMENT = 5
# #client_id ="QuYcN9pfIGGQKqqLrvHADt3w3xY8OcwHiCUObFti"
# #client_secret="tI8uYcvWDQdL2SxnldxUV54GMeZnnIW1Kw99C6qPmESJwCpslFRr2nkCalP5IF99a4JZ7UY7sp50gvd3BekJoFzZkbZYizfhgXzQohRXJjQ9jDoHb4xjsigXnghAxBBG"
#
# client_id="bxPJekIwxGNHwhgeJ0aM0JUIqZOupEP7oqTS1zVs"
# client_secret="m33iQHIuSIT40qRNQvsF989aGEoGOeSu9f2KgPLpPbn76fu0QAFE7hZVXiw6scmcGcKj4QjdFnIRImf9QRGvS4TyLb2LLWqm1mpyG2718jDXJuLdBFtTyC8RPHn0y0kh"
"""
Django settings for clinic_manager project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
URL_NGROK = 'fc7f-2001-ee0-4dc8-6600-c148-2e13-46e2-9006.ngrok-free.app'
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0jpo=x9qvt-*8h5@fae&@z50tvl*iu$#3#e*@$1ww&=h6844@j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.5', '127.0.0.1', 'localhost',URL_NGROK]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clinic_app',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders',
    'social_django',  # đăng nhập bằng fb
    # 'ckeditor_uploader',
    # "django_extensions", #https
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS
    'social_django.middleware.SocialAuthExceptionMiddleware',  # fb
    # 'social_django.context_processors.backends'
]

ROOT_URLCONF = 'clinic_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinic_manager.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'clinic1',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': ''  # mặc định localhost
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import cloudinary

cloudinary.config(
    cloud_name="dlkfozznl",
    api_key="216689541712763",
    api_secret="m_IQI6lLGClNtrf8ZeuG97Do4Fs",
    secure=True,
)

AUTH_USER_MODEL = 'clinic_app.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# setting cho facebook
# AUTHENTICATION_BACKENDS = [
#     'social_core.backends.facebook.FacebookOAuth2',
#     'django.contrib.auth.backends.ModelBackend',
# ]
# #
# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'home'
# LOGOUT_URL = 'logout'
# LOGOUT_REDIRECT_URL = 'login'
# #
# SOCIAL_AUTH_FACEBOOK_KEY = '893789679094872'
# SOCIAL_AUTH_FACEBOOK_SECRET = '1c4cf1353d5a18d9b66b934a73a74336'
# #
# # #for extra infor
# SOCIAL_AUTH_FACEBOOK_SCOPE = [
#     'email',
# ]

CORS_ALLOW_ALL_ORIGINS = True

# APP info
client_id="Y6UuGquIhKxI1yu60HiMrj4lsiVqvfJ1dWqGPuW8"
client_secret="rkQCq5uEz6Lfnm165tA9ADr1BTIthJPN92KIW995jGzhMAgFG3Pv6fV9TniBvyc8oior5SVlbubWmMnQS0ORQ6VooN2dPZSW8FG85F2EtGNAsEjpgKKrzMSYs7LccL8L"

# setting mail
EMAIL_HOST_USER = "levanhieu26012003@gmail.com"
MAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_PASSWORD = "qjpw wfda arwp emls"

MAX_APPOINTMENT = 5

# settings.py
ZALOPAY_APP_ID = 2553
ZALOPAY_KEY1 = 'PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL'
ZALOPAY_KEY2 = 'kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz'
ZALOPAY_ENDPOINT_CREATE = 'https://sb-openapi.zalopay.vn/v2/create'
ZALOPAY_ENDPOINT_QUERY = 'https://sb-openapi.zalopay.vn/v2/query'

# setting auto
# myapp/settings.py

# Cấu hình broker cho Celery (sử dụng Redis ở đây)
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'django-db'


CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = "Asia/Ho_Chi_Minh"

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'update-appointment-status-every-minute': {
        'task': 'clinic_app.tasks.send_notification_email',
        'schedule': crontab(minute='*/1'),  # Chạy mỗi phút
    },
'send-daily-report': {
        'task': 'clinic_app.tasks.check_appointment_fail',
        'schedule': crontab(hour=20),  # Chạy hàng ngày vào 7:30 sáng
    },
}

# cấu hình cho phép ngrok đang nhập admin
CSRF_TRUSTED_ORIGINS = ["https://" + URL_NGROK]

# câu leenhj chay beat
# Beat = "celery -A clinic_manager beat --loglevel=info"
# Worker = "celery -A clinic_manager worker --loglevel=info --concurrency 1 -P solo"

